# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-06 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttsx_goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='gkuncun',
            new_name='gkucun',
        ),
    ]
